twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        application_settings: '@App\Service\ApplicationSettingsService'
    form_themes: ['bootstrap_4_layout.html.twig']
