Project:
    type: object
    config:
        fields:
            id:
                type: "Int!"
            title:
                type: "String!"
            description:
                type: "String"
            filename:
                type: "String"
